version: "2"

services:
  heartbeats:
    image: ghcr.io/containeroo/heartbeats:v0.3.0
    hostname: heartbeats
    environment:
      - "SLACK_TOKEN=TOKEN"
      - "EMAIL_PASSWORD=SUPERSECRET"
    command:
      - --debug
      - --host
      - 0.0.0.0
    ports:
      - "8090:8090"
    volumes:
      - ./config.conf:/tmp/config.conf
    networks:
      - YOUR_NETWORK
