---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeats
  namespace: heartbeats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeats
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: heartbeats
    spec:
      containers:
        - name: heartbeats
          image: ghcr.io/gi8lino/heartbeats:v0.0.15
          imagePullPolicy: IfNotPresent
          args:
            - --config
            - /app/config.yaml
            - --host
            - 0.0.0.0
          env:
            - name: TZ
              value: Europe/Zurich
          envFrom:
            - secretRef:
                name: heartbeats
          ports:
            - name: http
              containerPort: 8090
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 3
            timeoutSeconds: 5
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 2
            periodSeconds: 30
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchLabels:
      #            app.kubernetes.io/name: alertmanager
      #        topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: config
          configMap:
            name: heartbeats
            defaultMode: 0755
